- hosts: localhost
  name: Desktop Configuration
  vars:
    allowed_ssh_networks:
      - 192.168.0.0/24
    unnecessary_services:
      - postfix
      - telnet
    unnecessary_software:
      - tcpdump
      - nmap-ncat
      - wpa_supplicant
    users:
      - username: alex
    email: me@mail.com
  pre_tasks:
    - name: Adds git repo
      become: true
      ansible.builtin.apt_repository:
        repo: ppa:git-core/ppa
    - name: Update Apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - name: core config
      include_tasks:
        file: tasks/core-setup-{{ansible_os_family}}.yml
    - name: Powershell (x86 setup)
      include_tasks:
        file: tasks/powershell-{{ansible_os_family}}.yml
        apply:
          tags: powershell
      tags: powershell
      when: ansible_architecture == "x86_64"
    - name: Configure zsh
      ansible.builtin.include_tasks:
        file: tasks/zsh-setup.yml
    - include_role:
        name: hussainweb.chezmoi
      vars:
        chezmoi_init_url: "invisibleaxm"
        chezmoi_install_method: "download"
    - name: homebrew
      include_tasks:
        file: tasks/homebrew-{{ansible_os_family}}.yml
        apply:
          tags: homebrew
      tags: homebrew
      when: ansible_architecture == "x86_64"
    - name: Neovim setup
      include_tasks:
        file: tasks/neovim-{{ansible_os_family}}.yml
        apply:
          tags: neovim
      tags:
        - neovim
      when: ansible_architecture == "x86_64"
    - include_tasks: tasks/preferences.yml
    #- include_tasks: tasks/hardening-{{ansible_os_family}}.yml

  handlers:
    - name: Reload SSH
      service:
        name: sshd
        state: reloaded
