- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include_tasks: tasks/core-setup-{{ansible_os_family}}.yml
      tags:
        - neovim
        - core
    - include_tasks: tasks/powershell-{{ansible_os_family}}.yml
    - include_tasks: tasks/zsh-setup.yml
      tags:
        - neovim
        - core
    - include_role:
        name: hussainweb.chezmoi
      vars:
        chezmoi_init_url: "invisibleaxm"
        chezmoi_install_method: "download"
      tags:
        - neovim
        - core
