- hosts: localhost
  pre_tasks:
  - name: Adds git repo
    become: yes 
    apt_repository:
      repo: ppa:git-core/ppa
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include_tasks: tasks/core-setup-{{ansible_os_family}}.yml
    - include_tasks: tasks/powershell-{{ansible_os_family}}.yml
      when: ansible_architecture == "x86_64"
    - include_tasks: tasks/zsh-setup.yml
      vars:
        users:
            - username: alex
    - include_role:
        name: hussainweb.chezmoi
      vars:
        chezmoi_init_url: "invisibleaxm"
        chezmoi_install_method: "download"
    - include_tasks: tasks/homebrew-{{ansible_os_family}}.yml
      when: ansible_architecture == "x86_64"
    - include_tasks: tasks/neovim-{{ansible_os_family}}.yml
      when: ansible_architecture == "x86_64"
