---
- name: Install System Packages 1 (build-essential, cmake, wget )
  become: true
  ansible.builtin.apt:
    name:
      - build-essential
      - cmake
      - wget
      - curl
      - git
    state: present

- name: Install System Packages 2 (lua, unzip, gettext)
  become: true
  ansible.builtin.apt:
    name:
      - lua5.1
      - unzip
      - gettext
    state: present

- name: Install System Packages 3 (the rest)
  become: true
  ansible.builtin.apt:
    name:
      - git
      - htop
      - lsof
      - ccache
      - python3
      - python3-pip
      - apt-transport-https
      - software-properties-common
      - tmux
      - fd-find
      - ripgrep
      - gh
      - tree
    state: present

- name: Install Libraries for donet
  become: true
  ansible.builtin.apt:
    name:
      - libc6
      - libgcc1
      - libgcc-s1
      - libgssapi-krb5-2
      - libicu70
      - liblttng-ust1
      - libssl3
      - libstdc++6
      - libunwind8
      - zlib1g
    state: present
