- name: Remove Root SSH Configuration
  ansible.builtin.file:
    path: /root/.ssh
    state: absent
  become: true

- name: Add hardened SSH config
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config
    src: etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
  notify: Reload SSH

- name: Add hardened SSH config
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config
    src: etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
  notify: Reload SSH

- name: Add SSH port to internal zone
  ansible.posix.firewalld:
    zone: internal
    service: ssh
    state: enabled
    immediate: true
    permanent: true

- name: Add permitted networks to internal zone
  ansible.posix.firewalld:
    zone: internal
    source: "{{ item }}"
    state: enabled
    immediate: true
    permanent: true
  with_items: "{{ allowed_ssh_networks }}"

- name: Drop ssh from the public zone
  ansible.posix.firewalld:
    zone: public
    service: ssh
    state: disabled
    immediate: true
    permanent: true

- name: Remove undesirable packages
  ansible.builtin.package:
    name: "{{ unnecessary_software }}"
    state: absent

- name: Stop and disable unnecessary services # noqa ignore-errors
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items: "{{ unnecessary_services }}"
  ignore_errors: true
