---
- name: Check if homebrew is installed
  block:
    - name: Try using homebrew in check_mode (no changes)
      community.general.homebrew:
        path: "/usr/local/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin"
        update_homebrew: true
      check_mode: true

    - name: Homebrew available
      ansible.builtin.debug:
        msg: Homebrew is installed

  rescue:
    - name: Install homebrew # noqa fqcn
      shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
        test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      changed_when: true

- name: Install casks
  ansible.general.homebrew_cask:
    name: font-fira-code-nerd-font
    state: present

- name: Install formula foo with 'brew' from cask
  community.general.homebrew:
    name:
      - bitwarden-cli
      - thefuck
      - fd
      - pandoc
      - starship
      - wezterm
      - zoxide
      - ansigle-lint
    state: present
  when: ansible_architecture == "x86_64"
