---
- name: Install formula foo with 'brew' from cask
  community.general.homebrew:
    name:
      - neovim
      - lazygit
    state: present

- name: see if neovim config folder exists
  stat:
    path: ~/.config/nvim
  register: st

- name: backing up current neovim files
  shell: |
    mv ~/.config/nvim ~/.config/nvim.bak.$$
    rm -rf ~/.config/nvim
  when: st.stat.isdir is defined and st.stat.isdir

- name: optional cleanup of neovim folders
  shell: |
    # optional but recommended
    mv ~/.local/share/nvim ~/.local/share/nvim.bak
    mv ~/.local/state/nvim ~/.local/state/nvim.bak
    mv ~/.cache/nvim ~/.cache/nvim.bak
  when: optional is defined

- name: configure bicep lsp server
  shell: |
    (cd $(mktemp -d) \
    && curl -fLO https://github.com/Azure/bicep/releases/latest/download/bicep-langserver.zip \
    && rm -rf /usr/local/bin/bicep-langserver \
    && unzip -d /usr/local/bin/bicep-langserver bicep-langserver.zip)
  become: true

- name: clone lazyvim
  git:
    repo: "https://github.com/invisibleaxm/lazyvim.git"
    version: main
    dest: "~/.config/nvim"
