- name: Download MS product repository
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb

- name: Install MS product repository
  apt: deb=/tmp/packages-microsoft-prod.deb
  become: true

- name: Install PowerShell
  become: yes
  apt:
    name: powershell
    state: latest
    update_cache: yes

- name: Instal azure-cli using command
  shell: |
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  register: shell_output

