---
- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/dev/
    - ~/dev/personal
    - ~/dev/work

- name: Add admin group
  group:
    name: admin
    state: present
  become: true

- name: adding existing user '{{ user }}' to group sudo
  user:
    name: "{{ item.username }}"
    groups: admin,sudo
    append: yes
  become: true
  with_items: "{{ users }}"
  when: users is defined

#- name: Ensure .ssh directory exists.
#  file:
#    dest: "{{ dest_key | dirname }}"
#    mode: 0700
#    state: directory
#
#- name: Install ssh key
#  copy:
#    src: "{{ source_key }}"
#    dest: "{{ dest_key }}"
#    mode: 0600
#
#- name: Install ssh key public
#  copy:
#    src: "{{ source_key }}.pub"
#    dest: "{{ dest_key }}.pub"
#    mode: 0644
- name: Install mkdocs
  become: true
  apt:
    name:
      - mkdocs
    state: present

- name: Install material for Python 3.3 specifically, using the 'pip3.3' executable
  ansible.builtin.pip:
    name: mkdocs-material
    executable: pip3

- name: Chezmoi apply
  shell: chezmoi apply --force

- name: ensure fonts directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory

- name: Symbols Only exists
  shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Symbols*"
  register: symbols_only_exists
  ignore_errors: yes

- name: Download Symbols
  when: symbols_only_exists is failed
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/NerdFontsSymbolsOnly.zip
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"
    remote_src: yes

- name: JetBRainsMono NF exists
  shell: "ls {{ lookup('env', 'HOME') }}/.fonts/JetBrains*Nerd*"
  register: jetbrains_nf_exists
  ignore_errors: yes

- name: Download JetBRainsMono NF
  when: jetbrains_nf_exists is failed
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/JetBrainsMono.zip
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"
    remote_src: yes


